### ISSUE TITLE
[Question] Is this mod built into 1.21 mekanism?

### ISSUE THREAD

**Issue by EvanHsieh0415** [Christofmeg/MekanismCardboardTooltip#1]
Just a question.

![Tooltip](https://github.com/user-attachments/assets/b3fe050a-5d1e-4e6c-ae95-0cb49839af89)
![Jade](https://github.com/user-attachments/assets/664845bf-1455-458e-b630-2581fa42e589)

![Mod Information](https://github.com/user-attachments/assets/c88691b6-9e6b-4c02-9f97-651b667811c9)

**Comment by Christofmeg** [comment]
I posted the mod on both CurseForge and Modrinth and announced it on r/feedthebeast. One of the Mekanism authors saw the post and integrated it into Mekanism version 1.20.4. As a result, the mod is now permanently included in Mekanism 1.20.4 and later versions
